Alter session  set container=orclpdb1;
ALTER DATABASE OPEN;

drop table QUESTIONS;
drop table Answers;
drop table user_question_response;
drop table users;
drop table certifications;
drop table feedback_question;

CREATE TABLE QUESTIONS
( QUESTION_ID NUMBER PRIMARY KEY,
QUESTION VARCHAR(2000)
);

CREATE SEQUENCE QUESTION_ID_SEQ START WITH 1 INCREMENT BY 1;


INSERT INTO QUESTIONS
VALUES(QUESTION_ID_SEQ.NEXTVAL, 'Which of the following SQL statements will authorize the user account JESSE to create tables in each and every user account in the
database?');

INSERT INTO QUESTIONS
VALUES(QUESTION_ID_SEQ.NEXTVAL, 'Which of the following is the system privilege that is required as a minimum to allow a user account to log in to the database?');

INSERT INTO QUESTIONS
VALUES(QUESTION_ID_SEQ.NEXTVAL, 'Which of the following is the system privilege that empowers the grantee to create an index in his or her own user account but not in
the accounts of others?');


SELECT * FROM QUESTIONS;


CREATE TABLE ANSWERS(
ANSWERS_ID NUMBER PRIMARY KEY,
ANSWER VARCHAR(1000),
QUESTION_ID NUMBER REFERENCES QUESTIONS(QUESTION_ID),
IS_CORRECT CHAR
);

CREATE SEQUENCE ANSWER_ID_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE TABLE',3,'Y');

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE ANY TABLE',3,'N');

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE INDEX',3,'N');

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE ANY INDEX',3,'N');

CREATE TABLE USERS
(USER_ID VARCHAR(15) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);


CREATE TABLE FEEDBACK_QUESTION
(FEEDBACK_QUESTION_ID NUMBER PRIMARY KEY,
FEEDBACK_QUESTION VARCHAR(2000),
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);


CREATE TABLE CERTIFICATIONS
(CERTIFICATION_ID NUMBER PRIMARY KEY,
CERTIFICATION_CODE VARCHAR(50),
CERTIFICATION_TITLE VARCHAR(150),
CERTIFICATION_BY_COMPANY VARCHAR(150),
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);

INSERT INTO CERTIFICATIONS VALUES(1,'1Z0-071','Oracle Database SQL','Oracle','bkumar',sysdate,'bkumar',sysdate);
commit;


 drop table USER_QUESTION_RESPONSE;
 
CREATE TABLE USER_QUESTION_RESPONSE
(USER_ID VARCHAR(15) REFERENCES USERS(USER_ID),
CERTIFICATION_ID NUMBER REFERENCES CERTIFICATIONS(CERTIFICATION_ID),
QUESTION_ID NUMBER REFERENCES QUESTIONS(QUESTION_ID), 
ANSWER_ID NUMBER REFERENCES ANSWERS(ANSWER_ID), 
USER_RESPONSE CHAR,
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);

INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,1,1,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,1,2,1,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,1,3,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,1,4,1,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,2,5,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,2,6,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,2,7,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,2,8,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,3,9,0,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,3,10,1,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,3,11,1,'bkumar',sysdate,'bkumar',sysdate);
INSERT INTO USER_QUESTION_RESPONSE VALUES('bkumar',1,3,12,0,'bkumar',sysdate,'bkumar',sysdate);

commit;

CREATE SEQUENCE CERTIFICATION_ID_SEQ START WITH 1 INCREMENT BY 1;

select * from USER_QUESTION_RESPONSE;

