CREATE TABLE QUESTIONS
( QUESTION_ID NUMBER PRIMARY KEY,
QUESTION VARCHAR(2000)
);

CREATE SEQUENCE QUESTION_ID_SEQ START WITH 1 INCREMENT BY 1;


INSERT INTO QUESTIONS
VALUES(QUESTION_ID_SEQ.NEXTVAL, 'Which of the following SQL statements will authorize the user account JESSE to create tables in each and every user account in the
database?');

INSERT INTO QUESTIONS
VALUES(QUESTION_ID_SEQ.NEXTVAL, 'Which of the following is the system privilege that is required as a minimum to allow a user account to log in to the database?');

INSERT INTO QUESTIONS
VALUES(QUESTION_ID_SEQ.NEXTVAL, 'Which of the following is the system privilege that empowers the grantee to create an index in his or her own user account but not in
the accounts of others?');


SELECT * FROM QUESTIONS;


CREATE TABLE ANSWERS(
ANSWERS_ID NUMBER PRIMARY KEY,
ANSWER VARCHAR(1000),
QUESTION_ID NUMBER REFERENCES QUESTIONS(QUESTION_ID),
IS_CORRECT CHAR
);


CREATE SEQUENCE ANSWERS_ID_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM ANSWERS;

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE TABLE',3,'Y');

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE ANY TABLE',3,'N');

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE INDEX',3,'N');

INSERT INTO ANSWERS
VALUES(ANSWERS_ID_SEQ.NEXTVAL, 'CREATE ANY INDEX',3,'N');

CREATE TABLE USERS
(USER_ID VARCHAR(15) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);


CREATE TABLE FEEDBACK_QUESTION
(FEEDBACK_QUESTION_ID NUMBER PRIMARY KEY,
FEEDBACK_QUESTION VARCHAR(2000),
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);


CREATE TABLE CERTIFICATIONS
(CERTIFICATION_ID NUMBER PRIMARY KEY,
CERTIFICATION_CODE VARCHAR(50),
CERTIFICATION_TITLE VARCHAR(150),
CERTIFICATION_BY_COMPANY VARCHAR(150),
CREATED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
CREATED_DATE DATE DEFAULT SYSDATE,
MODIFIED_BY VARCHAR(15) REFERENCES USERS(USER_ID),
MODIFIED_DATE DATE DEFAULT SYSDATE);

INSERT INTO CERTIFICATIONS VALUES(1,'1Z0-071','Oracle Database SQL','Oracle','bkumar',sysdate,'bkumar',sysdate);
commit;